### ISSUE TITLE
License

### ISSUE THREAD

**Issue by shsteven** [jaketmp/ePub-quicklook#35]
Thanks for the great work!

What's the license file for the source code? Can I use it in other ePub related projects?

**Comment by vitorgalvao** [comment]
Also interested in knowing this, for inclusion in [homebrew-cask](https://github.com/caskroom/homebrew-cask).

**Comment by jaketmp** [comment]
Hmm - I'll need to annotate the source appropriately, but I'll go with the Revised BSD License.

**Comment by jaketmp** [comment]
`LICENSE.md` added in commit df14dfc018a5668bf0606812eeaa9247b8ac08f2
