### ISSUE TITLE
Covers don't appear in QL previews since 10.10.2

### ISSUE THREAD

**Issue by chrisridd** [jaketmp/ePub-quicklook#40]
I think they worked in 10.10.1, but since 10.10.2 book covers appear as a "broken link" in the QL preview window.

The covers still appear on the custom Finder previews.

**Comment by PO40600** [comment]
Same issue for me on an iMac Retina

**Comment by Cocolinlin** [comment]
chrisridd
Can you built a corrected qlgenerator for some of us (who are dumb with Xcode) ?
Thanks in advance

**Comment by jaketmp** [comment]
Should be fixed in v1.7 on the releases page - thanks for the patch Chris!

**Comment by jaketmp** [comment]
Fixed in 4aba464a512a018b099a783c8ca25006cdc58dd4

**Comment by PO40600** [comment]
Thanks a lot
