### ISSUE TITLE
uncompiled files?

### ISSUE THREAD

**Issue by incandescentman** [jaketmp/ePub-quicklook#43]
I downloaded the .zip of this repository, but I don't see the epub.qlgenerator files. Instead I get folders with .c and .h and .m files. Do I need to compile this somehow? I tried `$ make` but that didn't work...

**Comment by jaketmp** [comment]
Did you choose the source code link from the [releases](https://github.com/jaketmp/ePub-quicklook/releases/latest) page rather than the `epub.qlgenerator.zip`?
