### ISSUE TITLE
Cover Preview Broken in El Capitan

### ISSUE THREAD

**Issue by mstolpm** [jaketmp/ePub-quicklook#44]
When browsing through a couple of epub files in Finder with the cursor keys and Quick Look opened, the title is updated for each selected file but the cover shown remains the one of the epub selected/displayed first. Moreover, covers show a small question mark in a blue square with a white border.

**Comment by jaketmp** [comment]
Simply rebuilding the existing code with Xcode 7 seems to have fixed this for me - I've updated the  binary in the [current release](https://github.com/jaketmp/ePub-quicklook/releases/download/v1.7/epub.qlgenerator.zip).

**Comment by zttt** [comment]
I had the same issue. In my case it was cause by conflicting with BookReader. Everything works fine after deleting the app.
