### ISSUE TITLE
Thumbnails of covers?

### ISSUE THREAD

**Issue by jefro108** [jaketmp/ePub-quicklook#46]
Is it possible to produce thumbnails of the covers like the Quicklook Video plugin is able to https://github.com/Marginal/QLVideo ?

**Comment by jaketmp** [comment]
The plugin does generate cover thumbnails when the Finder is in icon or column view (not list view).

**Comment by gennaios** [comment]
In list view, I've noticed when using smaller icons, the cover isn't shown. Is this possible to fix? Perhaps that is the used icon in Alfred and Spotlight results.
